# Generated by Django 3.2.9 on 2022-01-22 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0003_auto_20220114_1631'),
        ('rango', '0004_category_slug'),
    ]

    operations = [
    ]
